version: '3'
services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - url-shortener-net
    ports:
      - '8080:8080'
    environment:
      - MONGO_HOST=mongo0
    expose:
      - 8080
    depends_on:
      - mongo0
    logging:
      driver: json-file
    restart: always
  mongo0:
    image: mongo:latest
    container_name: mongo0
    networks:
      - url-shortener-net
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=us-root
      - MONGO_INITDB_ROOT_PASSWORD=toortoor6
      - MONGO_INITDB_DATABASE=url-shortener
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - url-sh-db-volume:/data/db
    restart: always
volumes:
  url-sh-db-volume:
networks:
  url-shortener-net:
    driver: bridge
